export { default as PlatformCategoryPanel } from './PlatformCategoryPanel';
export type { PlatformCategoryPanelProps } from './PlatformCategoryPanel';
export { default as PlatformTabBar } from './PlatformTabBar';
export type { PlatformTabBarProps, PlatformTabItem } from './PlatformTabBar';
export type { PlatformKind } from './types';
export { default as PlatformEmployeeCard } from './PlatformEmployeeCard';
export type { PlatformEmployeeCardProps, PlatformStat } from './PlatformEmployeeCard';
export { default as PlatformEmployeeDrawer } from './PlatformEmployeeDrawer';
export type { PlatformEmployeeDrawerProps } from './PlatformEmployeeDrawer';
export { default as PlatformKindDetailView } from './PlatformKindDetailView';
export type { PlatformDetailItem, PlatformDetailKind, PlatformKindDetailViewProps } from './PlatformKindDetailView';
export { default as PlatformResourceCard } from './PlatformResourceCard';
export type { PlatformResourceCardProps, PlatformResourceAccent } from './PlatformResourceCard';
export { platformResourceAccentStyles } from './PlatformResourceCard';
export { default as PlatformResourceDrawer } from './PlatformResourceDrawer';
export type { PlatformResourceDrawerProps } from './PlatformResourceDrawer';
