"""DSH worker: profile home, composition patch, and subprocess lifecycle.

The worker owns *how* DSH is launched; nothing about Staff, SOP or capability
selection. It:

1. materializes a ``DSH_HOME`` for this deployment (never ``~/.dsh``),
2. writes a StaffDeck profile patch (``cordis.patch.yml``) that
   - sets the persona to a neutral StaffDeck runtime persona (the real
     persona arrives per turn through pre-step context),
   - disables DSH's own filesystem/shell/web/subagent/todo/goal tools so the
     model can reach capabilities **only** through StaffDeck's proxies,
   - mounts the StaffDeck capability MCP server (Streamable HTTP) with the
     activation header forwarded from the environment,
   - points the LLM adapter at the deployment's OpenAI-compatible gateway,
3. launches ``dsh --profile sdk --patch <ours>`` through the official Python
   SDK's ``HarnessClient`` (stdio JSON-RPC), one process per Bridge session
   pool, and hands the live client to the ``EnginePort``.

Secrets never enter the patch file: the model API key and the activation
token are passed as environment variables and referenced with ``!!js``.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping

from staffdeck_dsh.contracts.errors import EngineUnavailable

PROFILE_NAME = "sdk"
PATCH_FILENAME = "staffdeck.patch.yml"
SDK_SRC_REL = ("python", "sdk", "src")

# DSH-native rows we disable so every capability travels through StaffDeck.
DISABLED_ROWS: tuple[str, ...] = (
    "tool-bash", "tool-pwsh", "tool-fs", "tool-fs-search", "tool-str-replace-editor",
    "skill", "skill-filesystem", "skill-badge", "tool-skill",
    "web", "web-search-deepseek", "web-fetch-http", "tool-web",
    "tool-subagent", "tool-subagent-fork", "tool-subagent-control", "tool-subagent-list-agents", "tool-subagent-report",
    "tool-workflow", "tool-todo", "tool-goal", "tool-ralph", "plan-mode", "goal", "goal-round-driver", "command-goal",
    "tool-jobs", "session-telemetry-otel", "session-title-llm",
)

RUNTIME_PERSONA = (
    "You are a StaffDeck digital employee runtime. Follow the persona, memory and SOP "
    "context injected at the start of each step. Use only the provided mcp__staffdeck__* tools "
    "to search knowledge, read skills, invoke business tools or run sandboxed commands; "
    "cite knowledge results with their [N] labels. Reply in the user's language."
)


@dataclass(frozen=True)
class DshWorkerConfig:
    dsh_root: Path                         # checkout containing apps/cli/lib/bin.js and python/sdk
    dsh_home: Path                         # deployment-owned DSH_HOME
    node_bin: str = "node"
    profile: str = PROFILE_NAME
    provider: str = "deepseek-official"
    model: str = "deepseek-v4-flash"
    model_base_url: str | None = None
    model_api_key: str | None = None
    # From the ModelConfig: "enabled" | "disabled" | "" (provider default) and "off" | "low" | "high" | "max" | "".
    thinking: str = ""
    reasoning_effort: str = ""
    permission_mode: str = "danger-full-access"   # StaffDeck enforces its own PEP; DSH sandbox is off
    initialize_timeout_seconds: float = 90.0
    request_timeout_seconds: float | None = 600.0
    extra_env: Mapping[str, str] = field(default_factory=dict)

    @property
    def bin_js(self) -> Path:
        return self.dsh_root / "apps" / "cli" / "lib" / "bin.js"

    @property
    def sdk_src(self) -> Path:
        return self.dsh_root.joinpath(*SDK_SRC_REL)

    def validate(self) -> None:
        if not self.bin_js.is_file():
            raise EngineUnavailable(f"DSH CLI not built: {self.bin_js} missing (run pnpm build:lib in {self.dsh_root})")
        if not self.sdk_src.is_dir():
            raise EngineUnavailable(f"DSH Python SDK not found at {self.sdk_src}")
        if shutil.which(self.node_bin) is None:
            raise EngineUnavailable(f"node binary {self.node_bin!r} not on PATH")


def _import_sdk(config: DshWorkerConfig) -> Any:
    path = str(config.sdk_src)
    if path not in sys.path:
        sys.path.insert(0, path)
    try:
        import deepseek_harness  # noqa: F401
    except ImportError as exc:  # pragma: no cover - depends on checkout
        raise EngineUnavailable(f"cannot import deepseek_harness from {path}: {exc}") from exc
    return sys.modules["deepseek_harness"]


def render_patch(*, mcp_url: str, persona: str = RUNTIME_PERSONA, disabled: tuple[str, ...] = DISABLED_ROWS) -> str:
    lines = [
        "# StaffDeck DSH profile overlay. Generated by staffdeck_dsh.bridge.worker; do not edit.",
        "- id: system-prompt",
        "  config:",
        f"    persona: {json.dumps(persona, ensure_ascii=False)}",
        "",
        "- id: llm-deepseek",
        "  config:",
        "    apiKeyEnv: STAFFDECK_MODEL_API_KEY",
        "    baseURL: !!js process.env.STAFFDECK_MODEL_BASE_URL",
        # Thinking policy follows the StaffDeck ModelConfig (extra_body.thinking.type); the adapter's own
        # default is reasoningEffort=high, which OpenAI-compatible gateways such as Qwen reject.
        "    thinking: !!js process.env.STAFFDECK_MODEL_THINKING || undefined",
        "    reasoningEffort: !!js process.env.STAFFDECK_MODEL_REASONING_EFFORT || undefined",
        "",
        "- id: agent-default-model",
        "  config:",
        "    provider: deepseek-official",
        "    model: !!js process.env.STAFFDECK_MODEL_NAME",
        "",
    ]
    for row in disabled:
        lines += [f"- id: {row}", "  disabled: true", ""]
    lines += [
        "- insert:",
        "    - id: staffdeck-capabilities",
        "      name: '@deepseek-ai/dsh-mcp-client'",
        "      config:",
        "        serverName: staffdeck",
        "        transport: streamable-http",
        f"        url: {json.dumps(mcp_url)}",
        "        headers:",
        "          x-staffdeck-activation: !!js process.env.STAFFDECK_ACTIVATION_TOKEN",
        "        toolCallTimeoutMs: 600000",
        "        failOnStartupError: true",
        "",
    ]
    return "\n".join(lines)


def materialize_home(config: DshWorkerConfig, *, mcp_url: str) -> Path:
    home = config.dsh_home
    home.mkdir(parents=True, exist_ok=True)
    patch = home / PATCH_FILENAME
    patch.write_text(render_patch(mcp_url=mcp_url), encoding="utf-8")
    return patch


class DshProcess:
    """One ``dsh --profile sdk`` subprocess wrapped by the official ``HarnessClient``.

    A process is bound to one activation token for its lifetime: the MCP header
    is read from the environment at plugin load. The Bridge therefore keeps one
    process per live turn (cheap: ~2s boot, reused across steps) and recycles
    it when the turn closes.
    """

    def __init__(self, config: DshWorkerConfig, *, activation_token: str, mcp_url: str, cwd: Path):
        config.validate()
        self.config = config
        self.activation_token = activation_token
        self.cwd = cwd
        self._sdk = _import_sdk(config)
        patch = materialize_home(config, mcp_url=mcp_url)
        env = {
            "DSH_HOME": str(config.dsh_home),
            "DSH_PERMISSION_MODE": config.permission_mode,
            "DSH_TELEMETRY_DISABLED": "1",
            "STAFFDECK_ACTIVATION_TOKEN": activation_token,
            "STAFFDECK_MODEL_NAME": config.model,
            **({"STAFFDECK_MODEL_THINKING": config.thinking} if config.thinking else {}),
            **({"STAFFDECK_MODEL_REASONING_EFFORT": config.reasoning_effort} if config.reasoning_effort else {}),
            **({"STAFFDECK_MODEL_BASE_URL": config.model_base_url} if config.model_base_url else {}),
            **({"STAFFDECK_MODEL_API_KEY": config.model_api_key} if config.model_api_key else {}),
            # llm-deepseek falls back to DEEPSEEK_* when the row leaves fields unset.
            **({"DEEPSEEK_BASE_URL": config.model_base_url} if config.model_base_url else {}),
            **({"DEEPSEEK_API_KEY": config.model_api_key} if config.model_api_key else {}),
            **dict(config.extra_env),
        }
        HarnessConfig = self._sdk.HarnessConfig
        HarnessClient = self._sdk.HarnessClient
        self.client = HarnessClient(
            HarnessConfig(
                profile=config.profile,
                dsh_home=str(config.dsh_home),
                env=env,
                cwd=str(cwd),
                initialize_timeout_seconds=config.initialize_timeout_seconds,
                request_timeout_seconds=config.request_timeout_seconds,
            ),
            _launch_args=(config.node_bin, str(config.bin_js), "--profile", config.profile, "--patch", str(patch)),
        )
        self._lock = threading.Lock()
        self._initialized = False

    def start(self) -> None:
        with self._lock:
            if self._initialized:
                return
            self.client.start()
            try:
                self.client.initialize(cwd=str(self.cwd), provider=self.config.provider, model=self.config.model)
            except Exception as exc:
                self.client.close()
                raise EngineUnavailable(f"DSH initialize failed: {exc}") from exc
            self._initialized = True

    def close(self) -> None:
        with self._lock:
            if not self._initialized:
                return
            try:
                self.client.close()
            finally:
                self._initialized = False

    @property
    def alive(self) -> bool:
        proc = getattr(self.client, "_proc", None)
        return bool(self._initialized and proc is not None and proc.poll() is None)


def default_config_from_settings(settings: Any) -> DshWorkerConfig:
    root = Path(str(getattr(settings, "dsh_root", "") or os.environ.get("DSH_ROOT", ""))).expanduser()
    home = Path(str(getattr(settings, "dsh_home", "") or os.environ.get("DSH_HOME", "") or (root / ".staffdeck-dsh-home"))).expanduser()
    return DshWorkerConfig(
        dsh_root=root,
        dsh_home=home,
        node_bin=str(getattr(settings, "dsh_node_bin", "node") or "node"),
        provider="deepseek-official",
        model=str(getattr(settings, "dsh_model", "") or "deepseek-v4-flash"),
        model_base_url=str(getattr(settings, "dsh_model_base_url", "") or "") or None,
        model_api_key=str(getattr(settings, "dsh_model_api_key", "") or "") or None,
        permission_mode=str(getattr(settings, "dsh_permission_mode", "danger-full-access") or "danger-full-access"),
    )
