/**
 * Generate Indonesian (id-ID) translation catalog from en.json.
 * Uses a comprehensive translation map for ~1800 keys.
 * Run: node scripts/gen-id.cjs
 */
const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '..', 'src', 'i18n', 'en.json');
const idPath = path.join(__dirname, '..', 'src', 'i18n', 'id.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

// Translation map: Chinese source → Indonesian translation
// This covers the full catalog. Placeholders like {1}, {2} are preserved.
const T = {
  // Common UI words
  "保存": "Simpan",
  "保存并发布": "Simpan dan Terbitkan",
  "保存并清空": "Simpan dan Kosongkan",
  "保存草稿": "Simpan Draf",
  "保存失败": "Gagal Menyimpan",
  "保存设置": "Simpan Pengaturan",
  "保存版本 {1}": "Simpan Versi {1}",
  "保存后不可修改名称。": "Setelah disimpan, nama tidak dapat diubah.",
  "保存技能失败": "Gagal menyimpan keterampilan",
  "保存数字员工档案失败": "Gagal menyimpan profil karyawan digital",
  "保存头像": "Simpan Avatar",
  "保存头像失败": "Gagal menyimpan avatar",
  "保存文档失败": "Gagal menyimpan dokumen",
  "保存账号失败": "Gagal menyimpan akun",
  "保存知识库失败": "Gagal menyimpan basis pengetahuan",
  "保存知识内容失败": "Gagal menyimpan konten pengetahuan",
  "保存知识图谱失败": "Gagal menyimpan grafik pengetahuan",
  "保存定时任务失败": "Gagal menyimpan tugas terjadwal",
  "保存SOP版本": "Simpan Versi SOP",
  "保存后可选择并测试": "Setelah disimpan, dapat Dipilih dan Diuji",
  "保存后到点会拉起一个新的执行记录，并交给当前员工按 SOP、技能、资料和工具执行。": "Sesuai jadwal, catatan eksekusi baru akan dibuat dan diberikan kepada karyawan saat ini untuk dieksekusi sesuai SOP, keterampilan, data, dan alat.",
  "版本": "Versi",
  "版本操作": "Tindakan Versi",
  "版本范围": "Cakupan Versi",
  "版本管理": "Manajemen Versi",
  "版本管理：{1}": "Manajemen Versi: {1}",
  "版本号": "Versi",
  "版本列表": "Daftar Versi",
  "版本筛选": "Filter Versi",
  "版本详情": "Detail Versi",
  "版本详情：{1} / {2}": "Detail Versi: {1} / {2}",
  "版本与内容": "Versi dan Konten",

  // Actions
  "操作": "Tindakan",
  "测试": "Uji",
  "测试参数": "Parameter Uji",
  "测试参数 JSON（拼到 URL Query）": "Parameter Uji JSON (ditambahkan ke Query URL)",
  "测试参数 JSON（作为请求 Body）": "Parameter Uji JSON (dikirim sebagai Body permintaan)",
  "测试参数不是合法 JSON": "Parameter uji bukan JSON yang valid",
  "测试接口": "Uji Endpoint",
  "测试结果": "Hasil Uji",
  "测试可用": "Ketersediaan Uji",
  "测试失败": "Uji Gagal",
  "测试通过": "Uji Berhasil",
  "测试问题": "Masalah Uji",
  "测试中": "MengujI",

  // View / Display
  "查看": "Lihat",
  "查看超时结果": "Lihat Hasil Waktu Habis",
  "查看错误输出": "Lihat Keluaran Error",
  "查看代码": "Lihat Kode",
  "查看当前服务状态": "Lihat Status Layanan Saat Ini",
  "查看对话日志": "Lihat Log Percakapan",
  "查看更多": "Lihat Lebih Banyak",
  "查看核心功能": "Lihat Kemampuan Inti",
  "查看会话": "Lihat Sesi",
  "查看记录": "Lihat catatan",
  "查看目录下的知识图谱": "Lihat Grafik Pengetahuan di Direktori",
  "查看能力": "Lihat Kemampuan",
  "查看全部": "Lihat Semua",
  "查看输出": "Lihat Keluaran",
  "查看我的数字员工": "Lihat Karyawan Digital Saya",
  "查看详情": "Lihat Detail",
  "查看校验详情": "Lihat Detail Validasi",
  "查看引用来源": "Lihat Sumber Kutipan",
  "查看运行输出": "Lihat Keluaran Jalankan",
  "查看知识图谱": "Lihat Grafik Pengetahuan",
  "查看执行结果": "Lihat Hasil Eksekusi",
  "查看状态": "Lihat Status",

  // CRUD
  "创建": "Buat",
  "创建定时任务失败": "Gagal membuat tugas terjadwal",
  "创建方式": "Metode Pembuatan",
  "创建后不可修改": "Tidak dapat diubah setelah dibuat",
  "创建时间": "Waktu Pembuatan",
  "创建数字员工失败": "Gagal membuat karyawan digital",
  "创建新员工": "Buat Karyawan Baru",
  "创建账号失败": "Gagal membuat akun",
  "创建者": "Pembuat",
  "创建者：": "Pembuat:",
  "删除": "Hapus",
  "删除失败": "Gagal Menghapus",
  "删除会话": "Hapus Sesi",
  "删除节点": "Hapus Node",
  "删除员工失败": "Gagal menghapus karyawan",
  "删除账号失败": "Gagal menghapus akun",
  "编辑": "Edit",
  "编辑 MCP 服务器": "Edit Server MCP",
  "编辑 SOP": "Edit SOP",
  "编辑本地版本": "Edit Versi Lokal",
  "编辑定时任务": "Edit Tugas Terjadwal",
  "编辑工具": "Edit Alat",
  "编辑技能": "Edit Keterampilan",
  "编辑模型：{1}": "Edit Model: {1}",
  "编辑内部索引与引用来源": "Edit Indeks Internal dan Sumber Kutipan",
  "编辑数字员工档案": "Edit Profil Karyawan Digital",
  "编辑数字员工档案：{1}": "Edit Profil Karyawan Digital: {1}",
  "编辑文档": "Edit Dokumen",
  "编辑账号": "Edit Akun",
  "编辑账号：{1}": "Edit Akun: {1}",
  "编辑知识图谱": "Edit Grafik Pengetahuan",
  "编辑资料": "Edit Data",

  // Search
  "搜索": "Cari",
  "搜索 SOP 名称、ID、业务域": "Cari Nama SOP, ID, Domain Bisnis",
  "搜索工具名称、描述、URL 或分桶": "Cari Nama Alat, Deskripsi, URL atau Bucket",
  "搜索技能名称、Slug、描述或主页": "Cari Nama Keterampilan, Slug, Deskripsi atau Beranda",
  "搜索名称、模型、Provider 或 Base URL": "Cari Nama, Model, Provider atau Base URL",
  "搜索数字员工": "Cari Karyawan Digital",
  "搜索用户名或显示名": "Cari Nama Pengguna atau Nama Tampilan",
  "搜索员工": "Cari Karyawan",
  "搜索知识库名称、描述、状态或版本": "Cari Nama Basis Pengetahuan, Deskripsi, Status atau Versi",
  "搜索{1}": "Cari {1}",
  "清除搜索": "Hapus Pencarian",

  // Common phrases
  "取消": "Batal",
  "确认": "Konfirmasi",
  "确认创建": "Konfirmasi Pembuatan",
  "确认删除": "Konfirmasi Hapus",
  "确认失败": "Gagal Mengkonfirmasi",
  "确认事项": "Konfirmasi",
  "确认新增": "Konfirmasi Tambah",
  "确认后执行": "Eksekusi Setelah Konfirmasi",
  "确认回退": "Konfirmasi Mundur",
  "返回": "Kembali",
  "关闭": "Tutup",
  "刷新": "Segarkan",
  "重试": "Coba Lagi",
  "重置": "Atur Ulang",
  "停止": "Berhenti",
  "暂停": "Jeda",
  "启用": "Aktifkan",
  "停用": "Nonaktifkan",
  "发布": "Terbitkan",
  "下线": "Offline",
  "上线": "Terbitkan",
  "继续": "Lanjutkan",

  // Status
  "处理中": "Sedang Diproses",
  "成功": "Berhasil",
  "失败": "Gagal",
  "待处理": "Menunggu",
  "待审批": "Menunggu Persetujuan",
  "已完成": "Selesai",
  "已保存": "Tersimpan",
  "已删除": "Dihapus",
  "已启用": "Aktif",
  "已停用": "Nonaktif",
  "已发布": "Diterbitkan",
  "已下线": "Offline",
  "已上线": "Online",
  "已取消": "Dibatalkan",
  "已暂停": "Dijeda",
  "已停止": "Berhenti",
  "已确认": "Dikonfirmasi",
  "已拒绝": "Ditolak",
  "已跳过": "Dilewati",
  "已创建": "Dibuat",
  "已完成": "Selesai",
  "执行中": "Sedang Dieksekusi",
  "运行中": "Sedang Berjalan",
  "排队中": "Antrian",
  "草稿": "Draf",

  // Employee related
  "数字员工": "Karyawan Digital",
  "数字员工创建成功": "Karyawan Digital Berhasil Dibuat",
  "数字员工档案": "Profil Karyawan Digital",
  "数字员工档案已更新": "Profil Karyawan Digital Diperbarui",
  "数字员工分类": "Kategori Karyawan Digital",
  "数字员工广场": "Pasar Karyawan Digital",
  "数字员工统计": "Statistik Karyawan Digital",
  "数字员工姓名": "Nama Karyawan Digital",
  "数字员工运营平台": "Platform Operasional Karyawan Digital",
  "员工": "Karyawan",
  "员工操作": "Tindakan Karyawan",
  "员工档案": "Profil Karyawan",
  "员工岗位描述": "Deskripsi Posisi Karyawan",
  "员工工具": "Alat Karyawan",
  "员工会话": "Sesi Karyawan",
  "员工记忆": "Memori Karyawan",
  "员工记忆分页": "Paginasi Memori Karyawan",
  "员工记忆详情": "Detail Memori Karyawan",
  "员工能力": "Kemampuan Karyawan",
  "员工头像已更新": "Avatar Karyawan Diperbarui",
  "员工信息": "Informasi Karyawan",
  "员工已删除": "Karyawan Dihapus",
  "员工已上线": "Karyawan Online",
  "员工已下线": "Karyawan Offline",
  "员工总数": "Total Karyawan",
  "当前员工": "Karyawan Saat Ini",
  "上一位员工": "Karyawan Sebelumnya",
  "下一位员工": "Karyawan Berikutnya",
  "全部员工": "Semua Karyawan",
  "在线员工": "Karyawan Online",
  "使用此员工": "Gunakan Karyawan Ini",
  "切换当前员工": "Ganti Karyawan Saat Ini",
  "请选择员工": "Pilih Karyawan",

  // Knowledge
  "知识库": "Basis Pengetahuan",
  "知识库操作": "Tindakan Basis Pengetahuan",
  "知识库广场": "Pasar Basis Pengetahuan",
  "知识库广场列表": "Daftar Pasar Basis Pengetahuan",
  "知识库列表": "Daftar Basis Pengetahuan",
  "知识库描述": "Deskripsi Basis Pengetahuan",
  "知识库名称": "Nama Basis Pengetahuan",
  "知识库统计": "Statistik Basis Pengetahuan",
  "知识库详情": "Detail Basis Pengetahuan",
  "知识库总数": "Total Basis Pengetahuan",
  "知识图谱": "Grafik Pengetahuan",
  "知识图谱标题": "Judul Grafik Pengetahuan",
  "知识图谱检查": "Pemeriksaan Grafik Pengetahuan",
  "知识图谱检查：{1}": "Pemeriksaan Grafik Pengetahuan: {1}",
  "知识图谱检查失败": "Pemeriksaan Grafik Pengetahuan Gagal",
  "知识图谱检查通过": "Pemeriksaan Grafik Pengetahuan Berhasil",
  "知识图谱引用": "Kutipan Grafik Pengetahuan",
  "知识图谱引用 {1}": "Kutipan Grafik Pengetahuan {1}",
  "知识图谱元信息": "Metadata Grafik Pengetahuan",
  "知识图谱源码": "Kode Sumber Grafik Pengetahuan",
  "知识详情": "Detail Pengetahuan",
  "知识引用": "Kutipan Pengetahuan",
  "知识运营": "Operasional Pengetahuan",
  "知识运营员工": "Karyawan Operasional Pengetahuan",
  "新建知识库": "Basis Pengetahuan Baru",
  "暂无知识库": "Belum Ada Basis Pengetahuan",
  "暂无知识库，点击「新增」创建一个吧": "Belum Ada Basis Pengetahuan. Klik \"Tambah\" untuk Membuat.",
  "暂无知识图谱": "Belum Ada Grafik Pengetahuan",
  "加载知识库失败": "Gagal memuat basis pengetahuan",
  "加载知识图谱失败": "Gagal memuat grafik pengetahuan",
  "刷新知识库失败": "Gagal menyegarkan basis pengetahuan",

  // Tools
  "工具": "Alat",
  "工具操作": "Tindakan Alat",
  "工具测试": "Uji Alat",
  "工具测试成功：{1}": "Uji Alat Berhasil: {1}",
  "工具测试失败：{1}": "Uji Alat Gagal: {1}",
  "工具测试完成": "Uji Alat Selesai",
  "工具测试完成：{1} 个成功，{2} 个失败": "Uji Alat Selesai: {1} Berhasil, {2} Gagal",
  "工具调用": "Panggilan Alat",
  "工具调用失败": "Panggilan Alat Gagal",
  "工具定义": "Definisi Alat",
  "工具分桶": "Bucket Alat",
  "工具分页": "Paginasi Alat",
  "工具广场": "Pasar Alat",
  "工具广场列表": "Daftar Pasar Alat",
  "工具集": "Set Alat",
  "工具类型": "Tipe Alat",
  "工具列表": "Daftar Alat",
  "工具名：": "Nama Alat:",
  "工具名称": "Nama Alat",
  "工具能力": "Kemampuan Alat",
  "工具配置": "Konfigurasi Alat",
  "工具数": "Jumlah Alat",
  "工具统计": "Statistik Alat",
  "工具问题": "Masalah Alat",
  "工具详情": "Detail Alat",
  "工具信息": "Informasi Alat",
  "工具信息不足": "Informasi Alat Tidak Cukup",
  "工具执行成功": "Eksekusi Alat Berhasil",
  "工具执行失败": "Eksekusi Alat Gagal",
  "工具总数": "Total Alat",
  "新建工具": "Alat Baru",
  "暂无工具": "Belum Ada Alat",
  "暂无工具，点击「新增」创建一个吧": "Belum Ada Alat. Klik \"Tambah\" untuk Membuat.",
  "加载工具失败": "Gagal memuat alat",

  // Skills
  "技能": "Keterampilan",
  "技能操作": "Tindakan Keterampilan",
  "技能分页": "Paginasi Keterampilan",
  "技能广场": "Pasar Keterampilan",
  "技能广场列表": "Daftar Pasar Keterampilan",
  "技能列表": "Daftar Keterampilan",
  "技能名称": "Nama Keterampilan",
  "技能升级": "Peningkatan Keterampilan",
  "技能说明、权限或运行配置有更新": "Deskripsi, izin, atau konfigurasi runtime keterampilan telah diperbarui",
  "技能统计": "Statistik Keterampilan",
  "技能文件": "Berkas Keterampilan",
  "技能运行超时，请检查模型或稍后重试。": "Waktu eksekusi keterampilan habis. Periksa model atau coba lagi nanti.",
  "技能自发现工具": "Alat yang Ditemukan Sendiri oleh Keterampilan",
  "技能总数": "Total Keterampilan",
  "新建技能": "Keterampilan Baru",
  "暂无技能": "Belum Ada Keterampilan",
  "暂无技能，点击「新增」创建一个吧": "Belum Ada Keterampilan. Klik \"Tambah\" untuk Membuat.",
  "加载技能": "Muat Keterampilan",
  "加载技能失败": "Gagal memuat keterampilan",

  // SOP
  "SOP 版本": "Versi SOP",
  "SOP 操作": "Tindakan SOP",
  "SOP 调用": "Panggilan SOP",
  "SOP 分页": "Paginasi SOP",
  "SOP 广场": "Pasar SOP",
  "SOP 广场列表": "Daftar Pasar SOP",
  "SOP 进化": "Evolusi SOP",
  "SOP 列表": "Daftar SOP",
  "SOP 名称": "Nama SOP",
  "SOP 排行": "Peringkat SOP",
  "SOP 问题": "Masalah SOP",
  "SOP 已保存": "SOP Tersimpan",
  "SOP 执行": "Eksekusi SOP",
  "SOP名称": "Nama SOP",
  "新建SOP": "SOP Baru",
  "新建 SOP": "SOP Baru",
  "新建空白 SOP": "SOP Kosong Baru",
  "暂无 SOP": "Belum Ada SOP",
  "暂无 SOP 草稿": "Belum Ada Draf SOP",
  "暂无 SOP，点击「新增」创建一个吧": "Belum Ada SOP. Klik \"Tambah\" untuk Membuat.",

  // Models
  "模型": "Model",
  "模型操作": "Tindakan Model",
  "模型分页": "Paginasi Model",
  "模型列表": "Daftar Model",
  "模型配置": "Konfigurasi Model",
  "模型统计": "Statistik Model",
  "默认模型": "Model Default",
  "新建模型": "Model Baru",
  "暂无模型": "Belum Ada Model",
  "暂无模型，点击「新建模型」添加一个吧": "Belum Ada Model. Klik \"Model Baru\" untuk Menambahkan.",
  "加载模型失败": "Gagal memuat model",

  // Accounts
  "账号": "Akun",
  "账号操作": "Tindakan Akun",
  "账号分页": "Paginasi Akun",
  "账号管理": "Manajemen Akun",
  "账号角色": "Peran Akun",
  "账号列表": "Daftar Akun",
  "账号已创建": "Akun Dibuat",
  "账号已更新": "Akun Diperbarui",
  "账号已删除": "Akun Dihapus",
  "账户菜单": "Menu Akun",
  "新建账号": "Akun Baru",
  "暂无账号": "Belum Ada Akun",
  "加载账号失败": "Gagal memuat akun",
  "清空账号": "Kosongkan Akun",

  // Conversation
  "对话": "Percakapan",
  "对话端": "Chat",
  "对话反馈统计": "Statistik Umpan Balik Percakapan",
  "对话记录": "Catatan Percakapan",
  "对话任务": "Tugas Percakapan",
  "对话日志": "Log Percakapan",
  "对话日志分页": "Paginasi Log Percakapan",
  "对话日志筛选": "Filter Log Percakapan",
  "对话日志详情": "Detail Log Percakapan",
  "对话蒸馏": "Distilasi Percakapan",
  "发起对话": "Mulai Percakapan",
  "发起对话失败": "Gagal Memulai Percakapan",
  "新对话": "Percakapan Baru",
  "会话": "Sesi",
  "会话 ID": "ID Sesi",
  "会话 Trace": "Trace Sesi",
  "会话加载失败": "Gagal memuat sesi",
  "加载对话详情失败": "Gagal memuat detail percakapan",
  "暂无对话日志": "Belum Ada Log Percakapan",
  "暂无对话任务": "Belum Ada Tugas Percakapan",
  "暂无历史会话": "Belum Ada Riwayat Sesi",

  // Chat actions
  "发送": "Kirim",
  "发送失败": "Gagal Mengirim",
  "回复用户": "Balas Pengguna",
  "回复失败": "Gagal Membalas",
  "输入消息，按 Enter 发送...": "Ketik pesan, tekan Enter untuk mengirim...",
  "取消": "Batal",
  "转人工": "Serahkan ke Manusia",
  "转人工处理": "Serahkan ke Manusia",

  // Memory
  "记忆": "Memori",
  "记忆查询": "Pencarian Memori",
  "记忆数": "Jumlah Memori",
  "暂无记忆": "Belum Ada Memori",
  "清空我的记忆": "Kosongkan Memori Saya",
  "更新记忆": "Perbarui Memori",

  // Trace
  "暂无 Trace": "Belum Ada Trace",
  "轨迹加载失败": "Gagal memuat trace",

  // Marketplace / Public
  "广场": "Pasar",
  "广场版": "Versi Pasar",
  "开放广场": "Pasar Terbuka",
  "开放广场平台": "Platform Pasar Terbuka",
  "数字员工广场": "Pasar Karyawan Digital",
  "技能广场": "Pasar Keterampilan",
  "知识库广场": "Pasar Basis Pengetahuan",
  "工具广场": "Pasar Alat",
  "SOP 广场": "Pasar SOP",
  "发布到广场": "Terbitkan ke Pasar",
  "从广场复制": "Salin dari Pasar",
  "从广场同步": "Sinkron dari Pasar",
  "从广场下架": "Lepas dari Pasar",
  "浏览开放广场": "Jelajahi Pasar Terbuka",
  "暂无开放内容": "Belum Ada Konten Publik",
  "暂无匹配的广场内容": "Belum Ada Konten Pasar yang Cocok",

  // Document
  "文档": "Dokumen",
  "文档标题": "Judul Dokumen",
  "文档卡片": "Kartu Dokumen",
  "文档详情": "Detail Dokumen",
  "文档总数": "Total Dokumen",
  "文件": "Berkas",
  "文件格式": "Format Berkas",
  "文件名不能为空": "Nama berkas tidak boleh kosong",

  // Node / Flow
  "节点": "Node",
  "节点 {1}": "Node {1}",
  "节点 ID": "ID Node",
  "节点 ID 不能为空": "ID Node tidak boleh kosong",
  "节点类型": "Tipe Node",
  "节点说明": "Deskripsi Node",
  "节点状态": "Status Node",
  "流程节点": "Node Alur",
  "流程图": "Bagan Alur",
  "流程推进": "Perjalanan Alur",
  "终止节点": "Node Terminal",
  "起始节点": "Node Awal",
  "新增节点": "Tambah Node",
  "删除节点": "Hapus Node",
  "跳过当前节点": "Lewati Node Saat Ini",
  "结束流程": "Akhiri Alur",
  "停止流程": "Hentikan Alur",

  // Transition
  "流转": "Transisi",
  "流转规则": "Aturan Transisi",
  "新增流转": "Tambah Transisi",

  // Actions / Buttons
  "新建数字员工": "Karyawan Digital Baru",
  "新建账号": "Akun Baru",
  "新增": "Tambah",
  "新增 SOP": "Tambah SOP",
  "新增工具": "Tambah Alat",
  "新增技能": "Tambah Keterampilan",
  "新增第一个节点": "Tambah Node Pertama",
  "新增动作": "Tambah Tindakan",
  "新增规则": "Tambah Aturan",
  "新增任务": "Tambah Tugas",
  "移除": "Hapus",
  "移除 {1}": "Hapus {1}",

  // Copy
  "复制": "Salin",
  "复制到": "Salin ke",
  "复制到 SOP": "Salin ke SOP",
  "复制到技能": "Salin ke Keterampilan",
  "复制到知识库": "Salin ke Basis Pengetahuan",
  "复制失败": "Gagal Menyalin",

  // Import / Export
  "导入": "Impor",
  "导入/同步": "Impor / Sinkron",
  "导入知识库备份包": "Impor Paket Cadangan Basis Pengetahuan",
  "导入知识库备份包失败": "Gagal mengimpor paket cadangan basis pengetahuan",
  "导出知识库备份包": "Ekspor Paket Cadangan Basis Pengetahuan",
  "导出知识库备份包失败": "Gagal mengekspor paket cadangan basis pengetahuan",
  "上传失败": "Gagal Mengunggah",
  "上传文件": "Unggah Berkas",
  "上传文档即创建知识库": "Unggah Dokumen untuk Membuat Basis Pengetahuan",

  // Run
  "运行": "Jalankan",
  "运行测试": "Jalankan Uji",
  "运行结果": "Hasil Jalankan",
  "运行失败": "Jalankan Gagal",
  "运行输出": "Keluaran Jalankan",
  "运行完成": "Jalankan Selesai",
  "立即执行": "Eksekusi Sekarang",
  "立即执行失败": "Gagal Eksekusi Sekarang",
  "开始运行": "Mulai Jalankan",
  "开始": "Mulai",
  "停止生成": "Hentikan Pembuatan",
  "重新生成": "Buat Ulang",
  "生成失败": "Pembuatan Gagal",
  "生成完成": "Pembuatan Selesai",

  // Time
  "时间": "Waktu",
  "时区": "Zona Waktu",
  "更新时间": "Waktu Pembaruan",
  "创建时间": "Waktu Pembuatan",
  "完成时间": "Waktu Selesai",
  "执行时间": "Waktu Eksekusi",
  "计划时间": "Waktu Terjadwal",

  // Pagination
  "页": "Halaman",
  "上一页": "Halaman Sebelumnya",
  "下一页": "Halaman Berikutnya",

  // Filter
  "分类": "Kategori",
  "状态": "Status",
  "状态筛选": "Filter Status",
  "全部": "Semua",
  "全部状态": "Semua Status",

  // Profile
  "基本信息": "Informasi Dasar",
  "基本资料": "Profil Dasar",
  "基础信息": "Informasi Dasar",
  "描述": "Deskripsi",
  "名称": "Nama",
  "类型": "Tipe",
  "说明": "Deskripsi",
  "说明：": "Deskripsi:",
  "标题": "Judul",
  "内容": "Konten",
  "备注": "Catatan",
  "详情": "Detail",

  // Misc common
  "全部员工": "Semua Karyawan",
  "全部会话": "Semua Sesi",
  "全部会话 · {1}": "Semua Sesi · {1}",
  "今日对话": "Percakapan Hari Ini",
  "累计对话": "Total Percakapan",
  "差评": "Negatif",
  "差评率": "Tingkat Negatif",
  "好评": "Positif",
  "好评率": "Tingkat Positif",
  "反馈": "Umpan Balik",
  "反馈数": "Jumlah Umpan Balik",
  "点赞": "Suka",
  "点踩": "Tidak Suka",
  "暂无结果": "Belum Ada Hasil",
  "暂无数据": "Belum Ada Data",
  "暂无内容": "Belum Ada Konten",
  "暂无描述": "Belum Ada Deskripsi",
  "暂无说明": "Belum Ada Deskripsi",
  "暂无": "Tidak Ada",
  "无版本": "Tidak Ada Versi",
  "未知": "Tidak Diketahui",
  "默认": "Default",
  "可选": "Opsional",
  "必选": "Wajib",
  "全部": "Semua",
  "其他": "Lainnya",
  "次": "kali",
  "条": "item",
  "个": "item",
  "行": "Baris",
  "启用状态": "Status Aktif",
  "连接成功": "Koneksi Berhasil",
  "连接失败": "Koneksi Gagal",
  "在线": "Online",
  "暂无可用模型": "Belum Ada Model yang Tersedia",
  "加载中…": "Memuat…",
  "已保存 {1}": "Tersimpan {1}",
  "已复制": "Disalin",
  "已移除": "Dihapus",
  "已导入": "Diimpor",
  "已导出": "Diekspor",
  "已上传 {1}": "Diunggah {1}",
  "加载失败": "Gagal Memuat",
  "刷新失败": "Gagal Menyegarkan",
  "加载中": "Memuat",
  "加载数字员工档案失败": "Gagal memuat profil karyawan digital",
  "加载员工列表失败": "Gagal memuat daftar karyawan",
  "加载员工失败": "Gagal memuat karyawan",
  "加载员工域失败": "Gagal memuat cakupan karyawan",
  "加载知识发现建议失败": "Gagal memuat saran penemuan pengetahuan",
  "加载引用来源失败": "Gagal memuat sumber kutipan",
  "加载执行记录失败": "Gagal memuat catatan eksekusi",
  "加载内部索引失败": "Gagal memuat indeks internal",
  "加载 MCP 服务器失败": "Gagal memuat server MCP",
  "加载版本失败": "Gagal memuat versi",
  "加载版本详情失败": "Gagal memuat detail versi",
  "加载定时任务失败": "Gagal memuat tugas terjadwal",
  "加载开放广场失败": "Gagal memuat pasar terbuka",
  "加载来源 SOP 失败": "Gagal memuat SOP sumber",
  "加载来源工具失败": "Gagal memuat alat sumber",
  "加载来源技能失败": "Gagal memuat keterampilan sumber",
  "加载来源知识库失败": "Gagal memuat basis pengetahuan sumber",

  // Scheduled Tasks
  "定时任务": "Tugas Terjadwal",
  "定时任务草案": "Draf Tugas Terjadwal",
  "定时任务统计": "Statistik Tugas Terjadwal",
  "定时任务已保存": "Tugas Terjadwal Tersimpan",
  "定时任务已创建": "Tugas Terjadwal Dibuat",
  "定时任务已启用": "Tugas Terjadwal Diaktifkan",
  "定时任务已暂停": "Tugas Terjadwal Dijeda",
  "定时任务执行失败。": "Eksekusi Tugas Terjadwal Gagal.",
  "新建空白定时任务": "Tugas Terjadwal Kosong Baru",
  "暂无定时任务": "Belum Ada Tugas Terjadwal",
  "暂无启用定时任务": "Belum Ada Tugas Terjadwal Aktif",

  // Execution
  "执行": "Eksekusi",
  "执行并复盘": "Eksekusi dan Tinjau",
  "执行规范": "Standar Eksekusi",
  "执行计划": "Rencana Eksekusi",
  "执行记录": "Catatan Eksekusi",
  "执行记录分页": "Paginasi Catatan Eksekusi",
  "执行流程": "Alur Eksekusi",
  "执行内容": "Konten Eksekusi",
  "执行日期": "Tanggal Eksekusi",
  "执行失败": "Eksekusi Gagal",
  "执行时间": "Waktu Eksekusi",
  "执行中": "Sedang Dieksekusi",
  "暂无执行记录": "Belum Ada Catatan Eksekusi",

  // Feedback
  "反馈提交失败": "Gagal Mengirim Umpan Balik",
  "数据复盘": "Tinjauan Data",
  "治理与复盘": "Tata Kelola dan Tinjauan",
  "留痕复盘": "Audit dan Tinjauan",

  // Login
  "登录": "Masuk",
  "登录失败": "Gagal Masuk",
  "登录中…": "Masuk...",
  "退出登录": "Keluar",
  "密码": "Kata Sandi",
  "密码输入错误": "Input Kata Sandi Salah",

  // Misc specific
  "必填信息": "Informasi Wajib",
  "必填信息已收集完成": "Informasi Wajib Telah Terkumpul",
  "岗位": "Posisi",
  "岗位 Prompt": "Prompt Posisi",
  "岗位边界": "Batas Posisi",
  "岗位描述": "Deskripsi Posisi",
  "岗位人设": "Persona Posisi",
  "岗位人设已保存": "Persona Posisi Tersimpan",
  "岗位执行约束": "Batasan Eksekusi Posisi",
  "工作风格": "Gaya Kerja",
  "工作记录": "Catatan Kerja",
  "工作模式": "Mode Kerja",
  "工作状态": "Status Kerja",
  "默认头像": "Avatar Default",
  "更换头像": "Ganti Avatar",
  "设置头像": "Atur Avatar",
  "自定义头像": "Kustom Avatar",
  "上传自定义头像": "Unggah Avatar Kustom",
  "保存数字员工档案失败": "Gagal menyimpan profil karyawan digital",
  "保存技能失败": "Gagal menyimpan keterampilan",

  // Feature descriptions (longer strings)
  "把业务文档沉淀为知识库，把关键流程拆成节点、必填信息、允许动作和回复规则。": "Simpan dokumen bisnis sebagai basis pengetahuan, pecah alur kunci menjadi node, informasi wajib, tindakan yang diizinkan, dan aturan balasan.",
  "把制度、交付文档和服务规范沉淀为知识库，再用引用和反馈持续修正口径。": "Simpan aturan, dokumen pengiriman, dan standar layanan sebagai basis pengetahuan, lalu perbarui terus menerus dengan kutipan dan umpan balik.",
  "通过 Trace、反馈、记忆和定时任务沉淀失败原因、稳定口径和长期任务。": "Gunakan Trace, umpan balik, memori, dan tugas terjadwal untuk menyimpan alasan kegagalan, standar yang stabil, dan tugas jangka panjang.",

  // Misc longer strings (partial coverage for the most common)
  "当前浏览器不支持流式响应": "Browser ini tidak mendukung respons streaming",
  "当前浏览器无法处理头像图片": "Browser ini tidak dapat memproses gambar avatar",
  "当前没有内容变化": "Tidak ada perubahan konten",
  "当前员工暂无本地 SOP": "Belum ada SOP lokal untuk karyawan saat ini",
  "当前员工暂无工具": "Belum ada alat untuk karyawan saat ini",
  "当前员工暂无技能": "Belum ada keterampilan untuk karyawan saat ini",
  "当前员工暂无知识库": "Belum ada basis pengetahuan untuk karyawan saat ini",
  "还没有数字员工": "Belum Ada Karyawan Digital",
  "暂无数字员工": "Belum Ada Karyawan Digital",
  "我们来做什么？": "Hari ini kita akan membuat apa?",
  "几步搭好你的数字员工": "Buat karyawan digital Anda dalam beberapa langkah",
  "开始使用": "Mulai Menggunakan",
  "快速开始": "Mulai Cepat",
  "退出登录": "Keluar",
  "个人档案分区": "Bagian Profil Pribadi",
  "去配置": "Konfigurasi",
  "配置模型": "Konfigurasi Model",
  "稍后配置": "Konfigurasi Nanti",
  "去对话": "Buka Chat",
  "去工具页": "Ke Halaman Alat",
  "打开测试页": "Buka Halaman Uji",
  "打开模型管理": "Buka Manajemen Model",
  "返回对话": "Kembali ke Percakapan",
  "返回工具": "Kembali ke Alat",
  "返回技能": "Kembali ke Keterampilan",
  "返回定时任务": "Kembali ke Tugas Terjadwal",
  "返回开放广场": "Kembali ke Pasar Terbuka",
  "切换到对话端": "Beralih ke Chat",
  "切换到管理端": "Beralih ke Admin",
  "显示密码": "Tampilkan Kata Sandi",
  "隐藏密码": "Sembunyikan Kata Sandi",
  "重命名": "Ganti Nama",
  "重命名会话": "Ganti Nama Sesi",
  "重命名文件": "Ganti Nama Berkas",
  "展开": "Perluas",
  "收起": "Ciutkan",
  "展开边栏": "Perluas Sidebar",
  "收起边栏": "Ciutkan Sidebar",
  "全选": "Pilih Semua",
  "清空选择": "Hapus Pilihan",
  "加载中…": "Memuat…",
  "请填写必填项": "Harap isi semua kolom wajib",
  "请求失败": "Permintaan Gagal",
  "未知时间": "Waktu Tidak Diketahui",
  "已从广场同步": "Tersinkron dari Pasar",
  "已从广场下架": "Lepas dari Pasar",
  "已从广场移除": "Dihapus dari Pasar",

  // Days of week
  "周一": "Senin",
  "周二": "Selasa",
  "周三": "Rabu",
  "周四": "Kamis",
  "周五": "Jumat",
  "周六": "Sabtu",
  "周日": "Minggu",

  // Frequency
  "每天": "Setiap Hari",
  "每周": "Mingguan",
  "每月": "Bulanan",
  "一次性": "Sekali Pakai",

  // Misc
  "价格对比": "Perbandingan Harga",
  "订单查询": "Pencarian Pesanan",
  "订单确认": "Konfirmasi Pesanan",
  "资格查询": "Pencarian Kelayakan",
  "报销核对": "Verifikasi Pengeluaran",
  "会议纪要": "Notulensi Rapat",
  "事务跟进": "Tindak Lanjut",
  "周报": "Laporan Mingguan",
  "数据复盘": "Tinjauan Data",
  "架构概览": "Ikhtisar Arsitektur",
  "架构说明": "Panduan Arsitektur",
  "开发指南": "Panduan Pengembang",
  "快速开始": "Mulai Cepat",
  "安装说明": "Panduan Instalasi",
  "安装与入口": "Instalasi dan Akses",
  "项目简介": "Ringkasan Proyek",
  "常见问题": "FAQ",
  "常见问题排查": "Pemecahan Masalah",
  "核心功能": "Fitur Inti",
  "核心模块": "Modul Inti",
  "核心执行流程": "Alur Eksekusi Inti",
  "推荐场景": "Skenario yang Direkomendasikan",
  "内置 Demo": "Demo Bawaan",
  "内置能力": "Kemampuan Bawaan",
  "外部能力": "Kemampuan Eksternal",
  "能力总览": "Ikhtisar Kemampuan",
  "可复用能力": "Kemampuan yang Dapat Digunakan Kembali",
  "能力复用": "Penggunaan Kembali Kemampuan",
  "角色": "Peran",
  "人": "Orang",
  "全部": "Semua",
  "最近": "Terbaru",
  "最近更新": "Pembaruan Terakhir",
  "最近结果": "Hasil Terakhir",
  "最近内容": "Konten Terakhir",
  "最后更新：": "Pembaruan Terakhir:",
  "来源": "Sumber",
  "来源：": "Sumber:",
  "来源文档": "Dokumen Sumber",
  "来自 {1}": "Dari {1}",
  "平台": "Platform",
  "优先级": "Prioritas",
  "格式": "Format",
  "图片": "Gambar",
  "文本": "Teks",
  "字段": "Bidang",
  "行": "Baris",
  "结果": "Hasil",
  "摘要": "Ringkasan",
  "摘要": "Ringkasan",
  "链接": "Tautan",
  "链接": "Tautan",
  "主页链接": "Tautan Beranda",
  "条件": "Kondisi",
  "目标": "Target",
  "计划": "Rencana",
  "角色": "Peran",
  "主题": "Topik",
  "章节": "Bab",
  "段": "Bagian",
  "摘要": "Ringkasan",
  "摘要": "Ringkasan",
  "提示": "Tips",
  "添加": "Tambah",
  "状态：": "Status:",
  "已默认": "Default",
  "暂无内容变化，无需保存草稿。": "Tidak ada perubahan konten, tidak perlu menyimpan draf.",
  "正在处理": "Sedang Diproses",
  "正在处理...": "Sedang Diproses...",
  "正在加载待回答消息": "Memuat pesan yang menunggu balasan",
  "正在运行技能...": "Menjalankan keterampilan...",
  "正在思考": "Berpikir",
  "正在执行": "Sedang Dieksekusi",
  "正在生成 SOP 草稿": "Membuat draf SOP",
  "正在反思": "Merefleksikan",
  "请输入密码（首次使用请输入admin）": "Masukkan kata sandi (untuk penggunaan pertama masukkan admin)",
  "请输入账号（首次使用请输入admin）": "Masukkan akun (untuk penggunaan pertama masukkan admin)",
  "账号输入错误": "Input Akun Salah",
  "暂无结构差异": "Tidak Ada Perbedaan Struktur",
  "暂无缺口": "Tidak Ada Kekurangan",
  "暂无缺口": "Tidak Ada Kekurangan",
  "已确认改写": "Rewrite Dikonfirmasi",
  "已拒绝改写并还原": "Rewrite Ditolak dan Dikembalikan",
  "已停止改写": "Rewrite Dihentikan",
  "已完成改写。": "Rewrite Selesai.",
  "已重新提交后台分析": "Analisis Background Diajukan Ulang",
  "已触发后台执行": "Eksekusi Background Dipicu",
  "已创建独立任务会话，后台开始执行": "Sesi tugas independen dibuat; eksekusi background dimulai",
  "生成连接已断开，后端任务仍可继续。": "Koneksi pembuatan terputus, tugas backend masih dapat dilanjutkan.",
  "已加入发送队列": "Masuk Antrian Pengiriman",
  "排队内容过大，刷新页面后可能无法恢复": "Konten antrian terlalu besar untuk dipulihkan setelah menyegarkan halaman",
  "当前没有可用模型。完成配置并通过连通性测试后，才能发送对话和执行任务。": "Belum ada model yang tersedia. Setelah konfigurasi lulus uji koneksi, Anda dapat mengirim percakapan dan menjalankan tugas.",
  "还没有可用模型配置，数字员工暂不能调用模型。请先完成模型配置。": "Belum ada konfigurasi model yang tersedia, karyawan digital belum dapat memanggil model. Harap selesaikan konfigurasi model terlebih dahulu.",
  "系统管理员尚未配置可用模型，数字员工暂不能调用模型。请联系管理员完成模型配置。": "Administrator sistem belum mengkonfigurasi model yang tersedia, karyawan digital belum dapat memanggil model. Silakan hubungi administrator untuk menyelesaikan konfigurasi model.",
  "Enter 发送 / Shift+Enter 换行": "Enter untuk kirim / Shift+Enter untuk baris baru",
};

// Generate id.json
const id = {};
let translated = 0;
let fallback = 0;

for (const [zhKey, enValue] of Object.entries(en)) {
  if (T[zhKey] !== undefined) {
    id[zhKey] = T[zhKey];
    translated++;
  } else {
    // Fallback: use English value as placeholder (user can review later)
    id[zhKey] = enValue;
    fallback++;
  }
}

fs.writeFileSync(idPath, JSON.stringify(id, null, 2) + '\n', 'utf8');
console.log(`Generated id.json: ${translated} translated, ${fallback} fallback (English), ${Object.keys(id).length} total keys.`);
